### PR TITLE
Adding TES support

### PR DESCRIPTION
**Pull request by Kelvinrr**
also a README edit, apparently

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Included updates to CI build files to prevent dependency clashes with Python 3.6

**Comment by Kelvinrr** [comment]
Question for @jlaura 

How big is too big for example files? I was reluctant to put the radiance data in here because the `.var` files are ~75MB a pop. So I opted for POS instead which is ~2MB in size. Do you think 75MB is too much?  Also, since adding one of every table in here would be overkill, and there exists table specific functions, there are a lot of `# pragma: no cover` lines in here.

**Comment by jlaura** [comment]
Single comment.  2MB is good.  75MB is too big.  Having said that, we could always link to data somewhere and use the request module to pull the data.

**Comment by jlaura** [comment]
:+1: Looks great!

**Pull request merged**
