### PR TITLE
Remove half pixel shift from bin scripts in light of #127

### LINKED ISSUE #135: socetnet2isis and isisnet2socet Applying Uneccessary 0.5 pixel shifts
As of #127 , plio has adopted a (0,0) pixel origin. Currently, the `socetnet2isis` and `isisnet2socet` bin scripts perform both an origin shift and a pixel origin correction. Based on the changes made to `to_isis()` and `from_isis()` in #127, the pixel origin correction in the bin scripts is now in error by 0.5 pixels in both the sample and line directions.

To fix this, the bin scripts should be changed to apply a pixel origin correction with a magnitude of 0.5 pixels, rather than 1.0 pixels. This should be as simple as modifying the following lines in the bin scripts:

https://github.com/USGS-Astrogeology/plio/blob/185a854774820cd0fc98c5621b4534fbf07f1d57/bin/socetnet2isis#L66-L67

https://github.com/USGS-Astrogeology/plio/blob/185a854774820cd0fc98c5621b4534fbf07f1d57/bin/isisnet2socet#L126-L127

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
Fixes #135 
Corrected a couple typos in `isisnet2socet` as well.

### CODE REVIEW

**Comment by jlaura** [comment]
I restarted the travis job - looks like everything passed except for a single job (which honestly, given the size of the build matrix is not surprising).

**Comment by jlaura** [comment]
@dpmayerUSGS I also want to confirm - since these bin scripts are not being independently tested, are you comfortable with the changes after testing locally?

**Comment by jlaura** [comment]
Last run on comment - I am not sure where coveralls is getting the code percentage change from. The drop is not related to this PR and checking their logs I am seeing this as well. I wonder if coveralls isn't taking the average of the build matrix and, since a job failed, that average is off.

**Comment by dpmayerUSGS** [comment]
> @dpmayerUSGS I also want to confirm - since these bin scripts are not being independently tested, are you comfortable with the changes after testing locally?

@jlaura Yes, I'm comfortable with the changes after testing locally.

**Comment by jlaura** [comment]
@acpaquette @tthatcher95 Can someone else also give this a review. If it looks good to you, please merge and then we can get someone to do a release.

**Comment by dpmayerUSGS** [comment]
@acpaquette @tthatcher95 Can one or both of you give this PR a review and merge if it looks good?

**Comment by jessemapel** [comment]
@jlaura Is this a good place to say, once the PR is approved, if there's no further comments with in X days, it gets merged?

**Comment by jlaura** [comment]
> @jlaura Is this a good place to say, once the PR is approved, if there's no further comments with in X days, it gets merged?

It is. Having said that, we also need to improve our turn around on PR reviews. Especially when the changes are small and the PR has been up for a while.

**Pull request merged**
