### PR TITLE
Added GXP support to read_gpf()

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
Modified `read_gpf()` in `io_bae.py` to support reading of either legacy Socet Set-style GPF files or new Socet GXP-style GPF files. Function now takes a boolean, `gxp` to flag whether function should interpret input file as SSET or GXP style, defaulst to SSET style for backwards compatibility. Removed unused variables from read_gpf(). Field names are now hard-coded in the function, rather than generated dynamically. The hints about field names in the GXP-style GPFs are just complicated enough that hard-coding a list of field names into the function was the simplest solution. Datatypes for each field were already hard-coded, so hard-coding the names is stylistically consistent.

Partially address #24

### CODE REVIEW

**Review by thareUSGS — APPROVED** [review]
new code looks good. This is a high-priority update and I agree it should be 100% backward compatible.

**Comment by jlaura** [comment]
@dpmayerUSGS Does this have tests associated with it? If not, can we get some tests added? I am not familiar with the format differences, so reviewing this is problematic sans tests. Thanks!

**Comment by jlaura** [comment]
Also - we should tick the version numbers on plio in this PR since we are adding functionality. Changes should be to the minor version (as this is an enhancement), so version 1.4.0. I believe the only place to change is: https://github.com/USGS-Astrogeology/plio/blob/master/setup.py

Once tests and version are good, I can merge and pull a new release. Should be <24 hours then before conda-forge sees that a new release has happened.

**Comment by dpmayerUSGS** [comment]
@jlaura No, there are no test associated with these changes. I don't know anything about how to write tests. I tested my changes on real data and @thareUSGS confirmed. That's the best I know how to do.

**Comment by jlaura** [comment]
@dpmayerUSGS Lots of example tests in here: https://github.com/USGS-Astrogeology/plio/blob/master/plio/io/tests/test_io_bae.py Let me know if you have questions. If the bae files are small, we could add reduced versions of them to the repo.

@acpaquette Any idea why existing tests are commented out?

**Comment by dpmayerUSGS** [comment]
@jlaura According to the commit history, it appears that you were the one, not Adam, who commented out all of the tests in test_io_bae.py with the note "Turns off bad bae tests that need to be fixed":
https://github.com/USGS-Astrogeology/plio/commit/30683d7df79f68fcc5896a34658fcdc38d7491c3#diff-fa724e67bc6ea2974dee3bb3ee1275db3438c164df8025d3d582cba9a9f06a49

I would be happy to mimic the existing tests in order to cover the new functionality, but the above commit message suggests that the tests are "bad," which would suggest I shouldn't use them as examples.

**Comment by jlaura** [comment]
:+1: I don't remember why they are bad. The syntax and setup for them is correct. If you prefer, check any of the other test_*.py files for examples using pytest.

**Comment by dpmayerUSGS** [comment]
I have added tests that are relevant to `read_gpf()` but I have left the other tests commented out and unchanged in "test_io_bae.py." I updated the example GXP-style GPF file and `git rm`'d another because it was superfluous.

I also ticked the version number to 1.4.0

**Review by jlaura — APPROVED** [review]

**Pull request merged**
