### PR TITLE
io_bae.py: Explicitly Set GPF/IPF Column data types on read

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
This PR addresses #70 and #23 by changing from a soft to hard conversion of data types in GPF and IPF fields in the `read_gpf()` and `read_ipf_str()` functions. The data types are now set explicitly for each column in the GPF and IPF data frames, consistent with the Socet Set specification for these files.

### CODE REVIEW

**Comment by jlaura** [comment]
With the CSM working going on, we inadvertently broke the CSM stuff.  I will work to get that fixed in the next few days and then this looks mergeable. 

Would you also please add appropriate test(s) to: https://github.com/USGS-Astrogeology/plio/blob/master/plio/io/tests/test_io_bae.py

**Comment by dpmayerUSGS** [comment]
@jlaura 
Thanks for taking a look at this.

The existing tests for the 2 affected functions will pass just fine.
What would be a good way to add tests for this?
Do I just add new example GPF and IPF files with point IDs that only contain numbers, plus corresponding truth data and run the existing tests, but parameterized with the new test and truth data?

**Comment by jlaura** [comment]
+1 for current passing. I would probably add a new test that reads, and then type checks columns to be the correct type. Then write to disk and read the first few lines naively in pure python to ensure that the types are as expected. That latter is tedious, but should mirror what Socet is doing in a different language?

**Comment by jlaura** [comment]
@dpmayerUSGS We have the conditional GDAL stuff all working. This PR needs:

- [ ] master merged
- [ ] tests added

**Comment by dpmayerUSGS** [comment]
Thanks @acpaquette for restarting Travis. It looks like one of the AppVeyor builds timed out (network issue?) and I don't think I can restart it myself. @jlaura can you restart the AppVeyor build? Or do I need to add some sort of trivial commit in order to trigger another build?

**Pull request merged**
