### PR TITLE
Moved remaining pyhat files

### PR DESCRIPTION
**Pull request by tthatcher95**
Removed remaining pyhat dependencies from plio

### CODE REVIEW

**Comment by jlaura** [comment]
Can you link to the associated PR in plio where these files are then added? I can review both then and we can merge at the same time.

**Comment by tthatcher95** [comment]
https://github.com/USGS-Astrogeology/PyHAT/pull/180

The last commit is adding them to PyHAT

**Comment by tthatcher95** [comment]
@jlaura The sooner we merge, the quicker we can check pyhat

**Comment by jlaura** [comment]
I am not going to get to this today. Please ping someone else to do a final review.

**Comment by tthatcher95** [comment]
@acpaquette @Kelvinrr This should be good to merge, so we can make sure that PyHAT passes.

**Comment by tthatcher95** [comment]
@ryanbanderson Can you review this and merge it? This needs to be merged in order for PyHAT to pass

**Comment by jlaura** [comment]
@tthatcher95 Sorry - I thought this was the PyHAT one. Someone else should review that one. You are good to go on this one. Apologies.

**Pull request merged**
