### PR TITLE
Adds TC1

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by ladoramkershner** [comment]
I visualized the data.db and I noticed that the new TC1 binary has a lot of new lines and I am concerned this will cause issues. For example, TC 2 looks like

```
('kaguya', 'Tc2', '{"Keyword1":{"InputGroup":"IsisCube,Instrument","InputKey":"SpacecraftName","InputPosition":["IsisCube","Instrument"],"OutputName":"Keyword1","Output ... (364 characters truncated) ... on":["IsisCube","Instrument"],"OutputName":"Keyword3","OutputPosition":["Group","SerialNumberKeywords"],"Translation":["*","*"]},"ObservationKeys":3}')
```
while TC1 looks like
```
('kaguya', 'Tc1', '{\n    "Keyword1": {\n        "InputGroup": "IsisCube,Instrument",\n        "InputKey": "SpacecraftName",\n        "InputPosition": [\n            "I ... (954 characters truncated) ...     "SerialNumberKeywords"\n        ],\n        "Translation": [\n            "*",\n            "*"\n        ]\n    },\n    "ObservationKeys": 3\n}\n')
```

I have tried running this on the kaguya subset I have and nothing was uploaded to the database. Most of the images I am using are TC2, but I do have a few TC1 images. However, I was able to get the images at least uploaded to the database before this update.

**Comment by jlaura** [comment]
Are you able to run the generate_isis_serial func using this PR? If so, it works. If not, what is the error?

**Comment by ladoramkershner** [comment]
I will check, my conda ate crap so I had to reinstall and remake my environment and it is a real big pain, but I am on it!!

**Comment by jlaura** [comment]
I just tested this manually using TC1 and TC2 data. Here are the results. Given that this is functioning well locally, I am going to merge.

```python
In [1]: from plio.io.isis_serial_number import generate_serial_number

In [2]: generate_serial_number('/Users/jlaura/Desktop/TC1S2B0_01_03021N353E0029.cub')
Out[2]: 'KAGUYA/TC1/2008-06-12T18:06:33.054878'

In [3]: generate_serial_number('/Users/jlaura/Desktop/TC2S2B0_01_03528N373E3530.cub')
Out[3]: 'KAGUYA/TC2/2008-07-24T09:46:43.645082'
```

**Pull request merged**
