### PR TITLE
Typo fixes in io_gpf.py

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
Column labels now match case of headers in Socet Set spec for GPF files.

### CODE REVIEW

**Comment by dpmayerUSGS** [comment]
I have no idea why the AppVeyor and Travis builds failed. I made a couple text changes in 1 file. Is there an issue with builds of PR's from forks?

**Comment by acpaquette** [comment]
@dpmayerUSGS Looks like the change in column name is not being mirrored in the tests associated with io_gpf. Need to change all instances of lat_y_North to lat_Y_North.

**Comment by dpmayerUSGS** [comment]
Ah shoot. Sorry, I’m just starting to learn about proper testing. 

Should I update the tests and submit another PR?

**Comment by acpaquette** [comment]
No problem! 

Yes, and you shouldn't need to submit another pr just push the changes to your master branch and it should automatically update this PR.

**Comment by thareUSGS** [comment]
The test should be fine. Look at bottom of the main code. There is an
instance of lat_y_North which needs to be updated.

**Pull request merged**
