### PR TITLE
Add essential functions from old transformations.py into socetnet2isi…

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
…s and isisnet2socet bin scripts

This PR address #80 by moving functions from the former `transformations.py` into the bin scripts themselves. Although this does not add integration testing for the transformation functions, the earlier `transformations.py` did not have associated integration tests either, so this is a lateral move from a testing standpoint. The emphasis is on restoring basic functionality.

### CODE REVIEW

**Comment by dpmayerUSGS** [comment]
@jlaura @acpaquette CI builds are failing apparently because of some changes to pytest (see #91 )that have absolutely nothing to do with the 2 files I changed as part of this PR. The changes in this PR involve files that have never been covered by CI and the changes are self-contained.

Can we go ahead and merge?

**Comment by jlaura** [comment]
#92 applies the necessary fix to the isis_serial tests and demonstrates how to parametrize tests. Note that #92 turns off the BAE tests. These tests are misusing fixtures (and output directories) in a number of ways. If the tests is testing a single file or a single expected, why is it parametrized at all? If test data or expected data are not being reused across tests, why are they being placed into fixtures?

**Comment by jlaura** [comment]
I commented out the whole file. Sloppy, but I need to get working on something else right now. This is why that PR is 'failing' - coverage drop > 0.1%.

**Comment by jlaura** [comment]
squashed and merged. Can you pull upstream master, merge it, and then update this PR?  That should have this passing then.

**Comment by dpmayerUSGS** [comment]
@jlaura Updated!
Thanks for taking the time to work on this today. I really appreciate it.

**Comment by jlaura** [comment]
If it passes, feel free to merge. I'm off for a while.

**Pull request merged**
