### PR TITLE
Updates travis to use environment.yml

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by jlaura** [comment]
This is partially in reference to #83 and the need to be able to cleanly set up a dev. env. A user can now be confident that the environment.yml is up to date with Travis.  Note that this does not solve being able to pip install or being able to use setup.py without conda.

**Comment by michaelaye** [comment]
Oh, is this a Github bug?

screenshot 2018-09-26 11 39 53

USGS-Astrogeology:master ?

**Comment by jlaura** [comment]
No, it is a human bug. We have been pushing to master. I need to make a plio release in the next few days (end of the fiscal). Then I'll rebase dev off master and push development to dev.  That is probably the safest approach.

**Comment by michaelaye** [comment]
I wasn't commenting on the fact that you pushed to master, many repos do. I was commenting on the fact that the text is only citing the organization name and is missing the actual repo name?

**Comment by jlaura** [comment]
ahh gotcha. yeah, no idea on that. that is strange.

**Pull request merged**
